### ISSUE TITLE
python binding: (a << 1) != (1 << a)

### ISSUE THREAD

**Issue by prokls** [stp/stp#195]
```python
import operator
import stp

def shift(op, param):
    s = stp.Solver()
    a = s.bitvec('a', 32)
    b = s.bitvec('b', 32)
    c = s.bitvec('c', 32)
    s.add(a == 3)
    s.add(b == op(a, param))
    s.add(c == op(param, a))
    assert s.check()
    assert s.model()['b'] == (3 << param if op is operator.lshift else 3 >> param)
    # works, but shouldn't
    assert s.model()['c'] == (3 << param if op is operator.lshift else 3 >> param)
    # does not work, but should
    #assert s.model()['c'] == (param << 3 if op is operator.lshift else param >> 3)

for i in range(0, 30):
    shift(operator.lshift, i)
    shift(operator.rshift, i)
```

I found a bug with the shifting operator. I assume the MWE is self-explanatory.

**Comment by prokls** [comment]
```python
import stp

def lshift(param):
    s = stp.Solver()
    a = s.bitvec('a', 32)
    b = s.bitvec('b', 32)
    c = s.bitvec('c', 32)
    s.add(a == 3)
    s.add(b == a << param)
    s.add(c == param << a)
    assert s.check()
    assert s.model()['b'] == (3 << param)
    # works, but shouldn't
    assert s.model()['c'] == (3 << param)
    # does not work, but should
    #assert s.model()['c'] == (param << 3)

def rshift(param):
    s = stp.Solver()
    a = s.bitvec('a', 32)
    b = s.bitvec('b', 32)
    c = s.bitvec('c', 32)
    s.add(a == 3)
    s.add(b == a >> param)
    s.add(c == param >> a)
    assert s.check()
    assert s.model()['b'] == (3 >> param)
    # works, but shouldn't
    assert s.model()['c'] == (3 >> param)
    # does not work, but should
    #assert s.model()['c'] == (param >> 3)

for i in range(1, 30):
    lshift(i)
    rshift(i)
```

Let's get rid of the ``operator`` library. I'm not sure ``a << b`` equals ``operator.lshift(a, b)`` in every situation.

**Comment by prokls** [comment]
The bug is obviously the [python datamodel](https://docs.python.org/dev/reference/datamodel.html?highlight=rlshift#object.__rlshift__) implemented wrongfully. See [bindings/python/stp/stp.py#L466](https://github.com/stp/stp/blob/master/bindings/python/stp/stp.py#L466):

```python
    def shl(self, other):
        return self._2w(_lib.vc_bvLeftShiftExprExpr, other)

    __lshift__ = shl
    __rlshift__ = shl
```

Actually ``a.__lshift__(b)`` equals ``b.__rlshift(a)``. Hence if one parameter is constant, the order gets screwed up.

```python
    def _2wo(self, cb, other):
        """Wrapper around double-expression with width STP functions
        with swapped operands."""
        other = self._toexpr(other)
        assert isinstance(other, Expr), \
            'Other object must be an Expr instance'
        assert self.width == other.width, 'Width must be equal'
        expr = cb(other.s.vc, self.width, other.expr, self.expr)
        return Expr(other.s, other.width, expr)

    def shl(self, other):
        return self._2w(_lib.vc_bvLeftShiftExprExpr, other)

    def shlo(self, other):
        return self._2wo(_lib.vc_bvLeftShiftExprExpr, other)

    __lshift__ = shl
    __rlshift__ = shlo

    def shr(self, other): 
        return self._2w(_lib.vc_bvRightShiftExprExpr, other)

    def shro(self, other):
        return self._2wo(_lib.vc_bvRightShiftExprExpr, other)

    __rshift__ = shr
    __rrshift__ = shro
```

This should fix it, but I need someone of the core team to look at it.

**Comment by msoos** [comment]
Wow, thanks for the detailed analysis!

I created a pull request that reflects your change. Can you please check that that's what you intended?

Thanks a lot in advance,

Mate

**Comment by prokls** [comment]
Your patch breaks the implementation:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 7, in lshift
  File "stp/stp.py", line 465, in shl
    return self._2w(_lib.vc_bvLeftShiftExprExpr, other)
AttributeError: 'Expr' object has no attribute '_2w'
```

1. You still need the ``_2w`` implementation for operations where the operands are not swapped. Hence methods in the data model which do not look like ``_r*__``.
2. Furthermore you need to extend that to all operations with swapped operands (including add, sub, …).

I attached a patch, which looks fine. Shifts pass the above testcase and other operators do not throw exceptions.

**Comment by msoos** [comment]
Cool, thanks a lot for that. And sorry for my misunderstanding. It was late in the night... By the way. In case you would like to contribute more to the python part or any other part, I'd be happy to give you access to the STP repo. Then you could make changes as you wish :)

**Comment by aclements** [comment]
This issue is definitely not fixed on the master branch.

I've sent PR #204 to fix, add tests for, and fill in the missing overloaded operators.
